// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: beneficios.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBeneficio = `-- name: CreateBeneficio :one
INSERT INTO beneficios (institucion_id, nombre)
VALUES ($1, $2)
RETURNING id, institucion_id, nombre, activo
`

type CreateBeneficioParams struct {
	InstitucionID pgtype.UUID `json:"institucion_id"`
	Nombre        string      `json:"nombre"`
}

func (q *Queries) CreateBeneficio(ctx context.Context, arg CreateBeneficioParams) (Beneficio, error) {
	row := q.db.QueryRow(ctx, createBeneficio, arg.InstitucionID, arg.Nombre)
	var i Beneficio
	err := row.Scan(
		&i.ID,
		&i.InstitucionID,
		&i.Nombre,
		&i.Activo,
	)
	return i, err
}

const getBeneficioPorID = `-- name: GetBeneficioPorID :one
SELECT b.id, b.institucion_id, b.nombre, b.activo, i.nombre AS institucion_nombre
FROM beneficios b
LEFT JOIN instituciones i ON i.id = b.institucion_id
WHERE b.id = $1
`

type GetBeneficioPorIDRow struct {
	ID                uuid.UUID   `json:"id"`
	InstitucionID     pgtype.UUID `json:"institucion_id"`
	Nombre            string      `json:"nombre"`
	Activo            bool        `json:"activo"`
	InstitucionNombre pgtype.Text `json:"institucion_nombre"`
}

func (q *Queries) GetBeneficioPorID(ctx context.Context, id uuid.UUID) (GetBeneficioPorIDRow, error) {
	row := q.db.QueryRow(ctx, getBeneficioPorID, id)
	var i GetBeneficioPorIDRow
	err := row.Scan(
		&i.ID,
		&i.InstitucionID,
		&i.Nombre,
		&i.Activo,
		&i.InstitucionNombre,
	)
	return i, err
}

const listBeneficios = `-- name: ListBeneficios :many
SELECT b.id, b.institucion_id, b.nombre, b.activo, i.nombre AS institucion_nombre
FROM beneficios b
LEFT JOIN instituciones i ON i.id = b.institucion_id
ORDER BY i.nombre ASC NULLS LAST, b.nombre ASC
`

type ListBeneficiosRow struct {
	ID                uuid.UUID   `json:"id"`
	InstitucionID     pgtype.UUID `json:"institucion_id"`
	Nombre            string      `json:"nombre"`
	Activo            bool        `json:"activo"`
	InstitucionNombre pgtype.Text `json:"institucion_nombre"`
}

func (q *Queries) ListBeneficios(ctx context.Context) ([]ListBeneficiosRow, error) {
	rows, err := q.db.Query(ctx, listBeneficios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBeneficiosRow{}
	for rows.Next() {
		var i ListBeneficiosRow
		if err := rows.Scan(
			&i.ID,
			&i.InstitucionID,
			&i.Nombre,
			&i.Activo,
			&i.InstitucionNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleBeneficioActivo = `-- name: ToggleBeneficioActivo :one
UPDATE beneficios SET activo = $2 WHERE id = $1 RETURNING id, institucion_id, nombre, activo
`

type ToggleBeneficioActivoParams struct {
	ID     uuid.UUID `json:"id"`
	Activo bool      `json:"activo"`
}

func (q *Queries) ToggleBeneficioActivo(ctx context.Context, arg ToggleBeneficioActivoParams) (Beneficio, error) {
	row := q.db.QueryRow(ctx, toggleBeneficioActivo, arg.ID, arg.Activo)
	var i Beneficio
	err := row.Scan(
		&i.ID,
		&i.InstitucionID,
		&i.Nombre,
		&i.Activo,
	)
	return i, err
}

const updateBeneficio = `-- name: UpdateBeneficio :one
UPDATE beneficios
SET nombre = $2, activo = $3, institucion_id = $4
WHERE id = $1
RETURNING id, institucion_id, nombre, activo
`

type UpdateBeneficioParams struct {
	ID            uuid.UUID   `json:"id"`
	Nombre        string      `json:"nombre"`
	Activo        bool        `json:"activo"`
	InstitucionID pgtype.UUID `json:"institucion_id"`
}

func (q *Queries) UpdateBeneficio(ctx context.Context, arg UpdateBeneficioParams) (Beneficio, error) {
	row := q.db.QueryRow(ctx, updateBeneficio,
		arg.ID,
		arg.Nombre,
		arg.Activo,
		arg.InstitucionID,
	)
	var i Beneficio
	err := row.Scan(
		&i.ID,
		&i.InstitucionID,
		&i.Nombre,
		&i.Activo,
	)
	return i, err
}

const countCanjesPorBeneficio = `-- name: CountCanjesPorBeneficio :one
SELECT COUNT(*) FROM canjes WHERE beneficio_id = $1
`

func (q *Queries) CountCanjesPorBeneficio(ctx context.Context, beneficioID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCanjesPorBeneficio, beneficioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBeneficio = `-- name: DeleteBeneficio :exec
DELETE FROM beneficios WHERE id = $1
`

func (q *Queries) DeleteBeneficio(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBeneficio, id)
	return err
}
