// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: beneficios.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createBeneficio = `-- name: CreateBeneficio :one
INSERT INTO beneficios (nombre)
VALUES ($1)
RETURNING id, nombre, activo
`

func (q *Queries) CreateBeneficio(ctx context.Context, nombre string) (Beneficio, error) {
	row := q.db.QueryRow(ctx, createBeneficio, nombre)
	var i Beneficio
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Activo,
	)
	return i, err
}

const getBeneficioPorID = `-- name: GetBeneficioPorID :one
SELECT id, nombre, activo FROM beneficios WHERE id = $1
`

func (q *Queries) GetBeneficioPorID(ctx context.Context, id uuid.UUID) (Beneficio, error) {
	row := q.db.QueryRow(ctx, getBeneficioPorID, id)
	var i Beneficio
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Activo,
	)
	return i, err
}

const listBeneficios = `-- name: ListBeneficios :many
SELECT id, nombre, activo FROM beneficios ORDER BY nombre ASC
`

func (q *Queries) ListBeneficios(ctx context.Context) ([]Beneficio, error) {
	rows, err := q.db.Query(ctx, listBeneficios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Beneficio{}
	for rows.Next() {
		var i Beneficio
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Activo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodasInstitucionesBeneficios = `-- name: ListTodasInstitucionesBeneficios :many
SELECT bi.beneficio_id, bi.institucion_id, i.nombre AS institucion_nombre
FROM beneficio_instituciones bi
JOIN instituciones i ON i.id = bi.institucion_id
ORDER BY bi.beneficio_id, i.nombre
`

func (q *Queries) ListTodasInstitucionesBeneficios(ctx context.Context) ([]BeneficioInstitucionRow, error) {
	rows, err := q.db.Query(ctx, listTodasInstitucionesBeneficios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BeneficioInstitucionRow{}
	for rows.Next() {
		var i BeneficioInstitucionRow
		if err := rows.Scan(
			&i.BeneficioID,
			&i.InstitucionID,
			&i.InstitucionNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstitucionesPorBeneficio = `-- name: ListInstitucionesPorBeneficio :many
SELECT bi.beneficio_id, bi.institucion_id, i.nombre AS institucion_nombre
FROM beneficio_instituciones bi
JOIN instituciones i ON i.id = bi.institucion_id
WHERE bi.beneficio_id = $1
ORDER BY i.nombre
`

func (q *Queries) ListInstitucionesPorBeneficio(ctx context.Context, beneficioID uuid.UUID) ([]BeneficioInstitucionRow, error) {
	rows, err := q.db.Query(ctx, listInstitucionesPorBeneficio, beneficioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BeneficioInstitucionRow{}
	for rows.Next() {
		var i BeneficioInstitucionRow
		if err := rows.Scan(
			&i.BeneficioID,
			&i.InstitucionID,
			&i.InstitucionNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBeneficioInstitucion = `-- name: InsertBeneficioInstitucion :exec
INSERT INTO beneficio_instituciones (beneficio_id, institucion_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertBeneficioInstitucionParams struct {
	BeneficioID   uuid.UUID `json:"beneficio_id"`
	InstitucionID uuid.UUID `json:"institucion_id"`
}

func (q *Queries) InsertBeneficioInstitucion(ctx context.Context, arg InsertBeneficioInstitucionParams) error {
	_, err := q.db.Exec(ctx, insertBeneficioInstitucion, arg.BeneficioID, arg.InstitucionID)
	return err
}

const deleteBeneficioInstituciones = `-- name: DeleteBeneficioInstituciones :exec
DELETE FROM beneficio_instituciones WHERE beneficio_id = $1
`

func (q *Queries) DeleteBeneficioInstituciones(ctx context.Context, beneficioID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBeneficioInstituciones, beneficioID)
	return err
}

const toggleBeneficioActivo = `-- name: ToggleBeneficioActivo :one
UPDATE beneficios SET activo = $2 WHERE id = $1 RETURNING id, nombre, activo
`

type ToggleBeneficioActivoParams struct {
	ID     uuid.UUID `json:"id"`
	Activo bool      `json:"activo"`
}

func (q *Queries) ToggleBeneficioActivo(ctx context.Context, arg ToggleBeneficioActivoParams) (Beneficio, error) {
	row := q.db.QueryRow(ctx, toggleBeneficioActivo, arg.ID, arg.Activo)
	var i Beneficio
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Activo,
	)
	return i, err
}

const updateBeneficio = `-- name: UpdateBeneficio :one
UPDATE beneficios
SET nombre = $2, activo = $3
WHERE id = $1
RETURNING id, nombre, activo
`

type UpdateBeneficioParams struct {
	ID     uuid.UUID `json:"id"`
	Nombre string    `json:"nombre"`
	Activo bool      `json:"activo"`
}

func (q *Queries) UpdateBeneficio(ctx context.Context, arg UpdateBeneficioParams) (Beneficio, error) {
	row := q.db.QueryRow(ctx, updateBeneficio,
		arg.ID,
		arg.Nombre,
		arg.Activo,
	)
	var i Beneficio
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Activo,
	)
	return i, err
}

const countCanjesPorBeneficio = `-- name: CountCanjesPorBeneficio :one
SELECT COUNT(*) FROM canjes WHERE beneficio_id = $1
`

func (q *Queries) CountCanjesPorBeneficio(ctx context.Context, beneficioID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCanjesPorBeneficio, beneficioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBeneficio = `-- name: DeleteBeneficio :exec
DELETE FROM beneficios WHERE id = $1
`

func (q *Queries) DeleteBeneficio(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBeneficio, id)
	return err
}
