// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: canjes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCanje = `-- name: CreateCanje :one
INSERT INTO canjes (cliente_id, beneficio_id, condicion_id, compra_id, usuario_id, descuento_aplicado)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, cliente_id, beneficio_id, condicion_id, compra_id, usuario_id, descuento_aplicado, fecha
`

type CreateCanjeParams struct {
	ClienteID         uuid.UUID `json:"cliente_id"`
	BeneficioID       uuid.UUID `json:"beneficio_id"`
	CondicionID       uuid.UUID `json:"condicion_id"`
	CompraID          uuid.UUID `json:"compra_id"`
	UsuarioID         uuid.UUID `json:"usuario_id"`
	DescuentoAplicado int32     `json:"descuento_aplicado"`
}

func (q *Queries) CreateCanje(ctx context.Context, arg CreateCanjeParams) (Canje, error) {
	row := q.db.QueryRow(ctx, createCanje,
		arg.ClienteID,
		arg.BeneficioID,
		arg.CondicionID,
		arg.CompraID,
		arg.UsuarioID,
		arg.DescuentoAplicado,
	)
	var i Canje
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.BeneficioID,
		&i.CondicionID,
		&i.CompraID,
		&i.UsuarioID,
		&i.DescuentoAplicado,
		&i.Fecha,
	)
	return i, err
}

const getFechaUltimoCanjeCondicion = `-- name: GetFechaUltimoCanjeCondicion :one
SELECT fecha FROM canjes
WHERE cliente_id = $1 AND condicion_id = $2
ORDER BY fecha DESC
LIMIT 1
`

type GetFechaUltimoCanjeCondicionParams struct {
	ClienteID   uuid.UUID `json:"cliente_id"`
	CondicionID uuid.UUID `json:"condicion_id"`
}

func (q *Queries) GetFechaUltimoCanjeCondicion(ctx context.Context, arg GetFechaUltimoCanjeCondicionParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getFechaUltimoCanjeCondicion, arg.ClienteID, arg.CondicionID)
	var fecha pgtype.Timestamptz
	err := row.Scan(&fecha)
	return fecha, err
}
