// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: canjes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCanje = `-- name: CreateCanje :one
INSERT INTO canjes (cliente_id, beneficio_id, condicion_id, compra_id, usuario_id, descuento_aplicado)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, cliente_id, beneficio_id, condicion_id, compra_id, usuario_id, descuento_aplicado, fecha
`

type CreateCanjeParams struct {
	ClienteID         uuid.UUID `json:"cliente_id"`
	BeneficioID       uuid.UUID `json:"beneficio_id"`
	CondicionID       uuid.UUID `json:"condicion_id"`
	CompraID          uuid.UUID `json:"compra_id"`
	UsuarioID         uuid.UUID `json:"usuario_id"`
	DescuentoAplicado int32     `json:"descuento_aplicado"`
}

func (q *Queries) CreateCanje(ctx context.Context, arg CreateCanjeParams) (Canje, error) {
	row := q.db.QueryRow(ctx, createCanje,
		arg.ClienteID,
		arg.BeneficioID,
		arg.CondicionID,
		arg.CompraID,
		arg.UsuarioID,
		arg.DescuentoAplicado,
	)
	var i Canje
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.BeneficioID,
		&i.CondicionID,
		&i.CompraID,
		&i.UsuarioID,
		&i.DescuentoAplicado,
		&i.Fecha,
	)
	return i, err
}
