// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categorias.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCategoria = `-- name: CreateCategoria :one
INSERT INTO categorias (nombre, seccion, orden)
VALUES ($1, $2, $3)
RETURNING id, nombre, seccion, orden
`

type CreateCategoriaParams struct {
	Nombre  string `json:"nombre"`
	Seccion string `json:"seccion"`
	Orden   int32  `json:"orden"`
}

func (q *Queries) CreateCategoria(ctx context.Context, arg CreateCategoriaParams) (Categoria, error) {
	row := q.db.QueryRow(ctx, createCategoria, arg.Nombre, arg.Seccion, arg.Orden)
	var i Categoria
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Seccion,
		&i.Orden,
	)
	return i, err
}

const getCategoriaPorID = `-- name: GetCategoriaPorID :one
SELECT id, nombre, seccion, orden FROM categorias WHERE id = $1
`

func (q *Queries) GetCategoriaPorID(ctx context.Context, id uuid.UUID) (Categoria, error) {
	row := q.db.QueryRow(ctx, getCategoriaPorID, id)
	var i Categoria
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Seccion,
		&i.Orden,
	)
	return i, err
}

const listCategorias = `-- name: ListCategorias :many
SELECT id, nombre, seccion, orden FROM categorias
ORDER BY seccion, orden, nombre
`

func (q *Queries) ListCategorias(ctx context.Context) ([]Categoria, error) {
	rows, err := q.db.Query(ctx, listCategorias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Categoria{}
	for rows.Next() {
		var i Categoria
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Seccion,
			&i.Orden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategoria = `-- name: UpdateCategoria :one
UPDATE categorias
SET nombre = $2, seccion = $3, orden = $4
WHERE id = $1
RETURNING id, nombre, seccion, orden
`

type UpdateCategoriaParams struct {
	ID      uuid.UUID `json:"id"`
	Nombre  string    `json:"nombre"`
	Seccion string    `json:"seccion"`
	Orden   int32     `json:"orden"`
}

func (q *Queries) UpdateCategoria(ctx context.Context, arg UpdateCategoriaParams) (Categoria, error) {
	row := q.db.QueryRow(ctx, updateCategoria,
		arg.ID,
		arg.Nombre,
		arg.Seccion,
		arg.Orden,
	)
	var i Categoria
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Seccion,
		&i.Orden,
	)
	return i, err
}
