// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clientes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCliente = `-- name: CreateCliente :one
INSERT INTO clientes (dni, nombre, email, institucion_id)
VALUES ($1, $2, $3, $4)
RETURNING id, dni, nombre, email, institucion_id, contador_infusiones, created_at
`

type CreateClienteParams struct {
	Dni           string        `json:"dni"`
	Nombre        string        `json:"nombre"`
	Email         pgtype.Text   `json:"email"`
	InstitucionID uuid.NullUUID `json:"institucion_id"`
}

func (q *Queries) CreateCliente(ctx context.Context, arg CreateClienteParams) (Cliente, error) {
	row := q.db.QueryRow(ctx, createCliente,
		arg.Dni,
		arg.Nombre,
		arg.Email,
		arg.InstitucionID,
	)
	var i Cliente
	err := row.Scan(
		&i.ID,
		&i.Dni,
		&i.Nombre,
		&i.Email,
		&i.InstitucionID,
		&i.ContadorInfusiones,
		&i.CreatedAt,
	)
	return i, err
}

const getClientePorDNI = `-- name: GetClientePorDNI :one
SELECT c.id, c.dni, c.nombre, c.email, c.institucion_id, c.contador_infusiones, c.created_at, i.nombre AS institucion_nombre
FROM clientes c
LEFT JOIN instituciones i ON i.id = c.institucion_id
WHERE c.dni = $1
`

type GetClientePorDNIRow struct {
	ID                 uuid.UUID          `json:"id"`
	Dni                string             `json:"dni"`
	Nombre             string             `json:"nombre"`
	Email              pgtype.Text        `json:"email"`
	InstitucionID      uuid.NullUUID      `json:"institucion_id"`
	ContadorInfusiones int32              `json:"contador_infusiones"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	InstitucionNombre  pgtype.Text        `json:"institucion_nombre"`
}

func (q *Queries) GetClientePorDNI(ctx context.Context, dni string) (GetClientePorDNIRow, error) {
	row := q.db.QueryRow(ctx, getClientePorDNI, dni)
	var i GetClientePorDNIRow
	err := row.Scan(
		&i.ID,
		&i.Dni,
		&i.Nombre,
		&i.Email,
		&i.InstitucionID,
		&i.ContadorInfusiones,
		&i.CreatedAt,
		&i.InstitucionNombre,
	)
	return i, err
}

const getClientePorID = `-- name: GetClientePorID :one
SELECT c.id, c.dni, c.nombre, c.email, c.institucion_id, c.contador_infusiones, c.created_at, i.nombre AS institucion_nombre
FROM clientes c
LEFT JOIN instituciones i ON i.id = c.institucion_id
WHERE c.id = $1
`

type GetClientePorIDRow struct {
	ID                 uuid.UUID          `json:"id"`
	Dni                string             `json:"dni"`
	Nombre             string             `json:"nombre"`
	Email              pgtype.Text        `json:"email"`
	InstitucionID      uuid.NullUUID      `json:"institucion_id"`
	ContadorInfusiones int32              `json:"contador_infusiones"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	InstitucionNombre  pgtype.Text        `json:"institucion_nombre"`
}

func (q *Queries) GetClientePorID(ctx context.Context, id uuid.UUID) (GetClientePorIDRow, error) {
	row := q.db.QueryRow(ctx, getClientePorID, id)
	var i GetClientePorIDRow
	err := row.Scan(
		&i.ID,
		&i.Dni,
		&i.Nombre,
		&i.Email,
		&i.InstitucionID,
		&i.ContadorInfusiones,
		&i.CreatedAt,
		&i.InstitucionNombre,
	)
	return i, err
}

const incrementarContadorInfusiones = `-- name: IncrementarContadorInfusiones :exec
UPDATE clientes
SET contador_infusiones = contador_infusiones + $2
WHERE id = $1
`

type IncrementarContadorInfusionesParams struct {
	ID                 uuid.UUID `json:"id"`
	ContadorInfusiones int32     `json:"contador_infusiones"`
}

func (q *Queries) IncrementarContadorInfusiones(ctx context.Context, arg IncrementarContadorInfusionesParams) error {
	_, err := q.db.Exec(ctx, incrementarContadorInfusiones, arg.ID, arg.ContadorInfusiones)
	return err
}

const listClientes = `-- name: ListClientes :many
SELECT c.id, c.dni, c.nombre, c.email, c.institucion_id, c.contador_infusiones, c.created_at, i.nombre AS institucion_nombre
FROM clientes c
LEFT JOIN instituciones i ON i.id = c.institucion_id
ORDER BY c.created_at DESC
LIMIT 50
`

type ListClientesRow struct {
	ID                 uuid.UUID          `json:"id"`
	Dni                string             `json:"dni"`
	Nombre             string             `json:"nombre"`
	Email              pgtype.Text        `json:"email"`
	InstitucionID      uuid.NullUUID      `json:"institucion_id"`
	ContadorInfusiones int32              `json:"contador_infusiones"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	InstitucionNombre  pgtype.Text        `json:"institucion_nombre"`
}

func (q *Queries) ListClientes(ctx context.Context) ([]ListClientesRow, error) {
	rows, err := q.db.Query(ctx, listClientes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClientesRow{}
	for rows.Next() {
		var i ListClientesRow
		if err := rows.Scan(
			&i.ID,
			&i.Dni,
			&i.Nombre,
			&i.Email,
			&i.InstitucionID,
			&i.ContadorInfusiones,
			&i.CreatedAt,
			&i.InstitucionNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reiniciarContadorInfusiones = `-- name: ReiniciarContadorInfusiones :exec
UPDATE clientes
SET contador_infusiones = 0
WHERE id = $1
`

func (q *Queries) ReiniciarContadorInfusiones(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, reiniciarContadorInfusiones, id)
	return err
}

const updateCliente = `-- name: UpdateCliente :one
UPDATE clientes
SET nombre = $2,
    email = $3,
    institucion_id = $4
WHERE id = $1
RETURNING id, dni, nombre, email, institucion_id, contador_infusiones, created_at
`

type UpdateClienteParams struct {
	ID            uuid.UUID     `json:"id"`
	Nombre        string        `json:"nombre"`
	Email         pgtype.Text   `json:"email"`
	InstitucionID uuid.NullUUID `json:"institucion_id"`
}

func (q *Queries) UpdateCliente(ctx context.Context, arg UpdateClienteParams) (Cliente, error) {
	row := q.db.QueryRow(ctx, updateCliente,
		arg.ID,
		arg.Nombre,
		arg.Email,
		arg.InstitucionID,
	)
	var i Cliente
	err := row.Scan(
		&i.ID,
		&i.Dni,
		&i.Nombre,
		&i.Email,
		&i.InstitucionID,
		&i.ContadorInfusiones,
		&i.CreatedAt,
	)
	return i, err
}
