// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compras.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCompra = `-- name: CreateCompra :one
INSERT INTO compras (cliente_id, usuario_id, subtotal, descuento, total)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, cliente_id, usuario_id, subtotal, descuento, total, fecha
`

type CreateCompraParams struct {
	ClienteID uuid.UUID `json:"cliente_id"`
	UsuarioID uuid.UUID `json:"usuario_id"`
	Subtotal  int32     `json:"subtotal"`
	Descuento int32     `json:"descuento"`
	Total     int32     `json:"total"`
}

func (q *Queries) CreateCompra(ctx context.Context, arg CreateCompraParams) (Compra, error) {
	row := q.db.QueryRow(ctx, createCompra,
		arg.ClienteID,
		arg.UsuarioID,
		arg.Subtotal,
		arg.Descuento,
		arg.Total,
	)
	var i Compra
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.UsuarioID,
		&i.Subtotal,
		&i.Descuento,
		&i.Total,
		&i.Fecha,
	)
	return i, err
}

const createDetalleCompra = `-- name: CreateDetalleCompra :exec
INSERT INTO detalle_compra (compra_id, producto_id, cantidad, precio_unitario)
VALUES ($1, $2, $3, $4)
`

type CreateDetalleCompraParams struct {
	CompraID       uuid.UUID `json:"compra_id"`
	ProductoID     uuid.UUID `json:"producto_id"`
	Cantidad       int32     `json:"cantidad"`
	PrecioUnitario int32     `json:"precio_unitario"`
}

func (q *Queries) CreateDetalleCompra(ctx context.Context, arg CreateDetalleCompraParams) error {
	_, err := q.db.Exec(ctx, createDetalleCompra,
		arg.CompraID,
		arg.ProductoID,
		arg.Cantidad,
		arg.PrecioUnitario,
	)
	return err
}

const listComprasPorCliente = `-- name: ListComprasPorCliente :many
SELECT id, cliente_id, usuario_id, subtotal, descuento, total, fecha FROM compras
WHERE cliente_id = $1
ORDER BY fecha DESC
`

func (q *Queries) ListComprasPorCliente(ctx context.Context, clienteID uuid.UUID) ([]Compra, error) {
	rows, err := q.db.Query(ctx, listComprasPorCliente, clienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Compra{}
	for rows.Next() {
		var i Compra
		if err := rows.Scan(
			&i.ID,
			&i.ClienteID,
			&i.UsuarioID,
			&i.Subtotal,
			&i.Descuento,
			&i.Total,
			&i.Fecha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
