// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compras.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listComprasPorCliente = `-- name: ListComprasPorCliente :many
SELECT id, cliente_id, usuario_id, subtotal, descuento, total, fecha FROM compras
WHERE cliente_id = $1
ORDER BY fecha DESC
`

func (q *Queries) ListComprasPorCliente(ctx context.Context, clienteID uuid.UUID) ([]Compra, error) {
	rows, err := q.db.Query(ctx, listComprasPorCliente, clienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Compra{}
	for rows.Next() {
		var i Compra
		if err := rows.Scan(
			&i.ID,
			&i.ClienteID,
			&i.UsuarioID,
			&i.Subtotal,
			&i.Descuento,
			&i.Total,
			&i.Fecha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
