// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compras.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listComprasEnRango = `-- name: ListComprasEnRango :many
SELECT
    c.id, c.cliente_id, c.usuario_id, c.subtotal, c.descuento, c.total, c.fecha,
    cl.nombre AS cliente_nombre,
    cl.dni    AS cliente_dni
FROM compras c
JOIN clientes cl ON cl.id = c.cliente_id
WHERE c.fecha >= $1 AND c.fecha < $2
ORDER BY c.fecha DESC
`

type ListComprasEnRangoRow struct {
	ID            uuid.UUID          `json:"id"`
	ClienteID     uuid.UUID          `json:"cliente_id"`
	UsuarioID     uuid.UUID          `json:"usuario_id"`
	Subtotal      int32              `json:"subtotal"`
	Descuento     int32              `json:"descuento"`
	Total         int32              `json:"total"`
	Fecha         pgtype.Timestamptz `json:"fecha"`
	ClienteNombre string             `json:"cliente_nombre"`
	ClienteDni    string             `json:"cliente_dni"`
}

func (q *Queries) ListComprasEnRango(ctx context.Context, desde, hasta pgtype.Timestamptz) ([]ListComprasEnRangoRow, error) {
	rows, err := q.db.Query(ctx, listComprasEnRango, desde, hasta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComprasEnRangoRow{}
	for rows.Next() {
		var i ListComprasEnRangoRow
		if err := rows.Scan(
			&i.ID,
			&i.ClienteID,
			&i.UsuarioID,
			&i.Subtotal,
			&i.Descuento,
			&i.Total,
			&i.Fecha,
			&i.ClienteNombre,
			&i.ClienteDni,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCompra = `-- name: CreateCompra :one
INSERT INTO compras (cliente_id, usuario_id, subtotal, descuento, total)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, cliente_id, usuario_id, subtotal, descuento, total, fecha
`

type CreateCompraParams struct {
	ClienteID uuid.UUID `json:"cliente_id"`
	UsuarioID uuid.UUID `json:"usuario_id"`
	Subtotal  int32     `json:"subtotal"`
	Descuento int32     `json:"descuento"`
	Total     int32     `json:"total"`
}

func (q *Queries) CreateCompra(ctx context.Context, arg CreateCompraParams) (Compra, error) {
	row := q.db.QueryRow(ctx, createCompra,
		arg.ClienteID,
		arg.UsuarioID,
		arg.Subtotal,
		arg.Descuento,
		arg.Total,
	)
	var i Compra
	err := row.Scan(
		&i.ID,
		&i.ClienteID,
		&i.UsuarioID,
		&i.Subtotal,
		&i.Descuento,
		&i.Total,
		&i.Fecha,
	)
	return i, err
}

const createDetalleCompra = `-- name: CreateDetalleCompra :exec
INSERT INTO detalle_compra (compra_id, producto_id, cantidad, precio_unitario)
VALUES ($1, $2, $3, $4)
`

type CreateDetalleCompraParams struct {
	CompraID       uuid.UUID `json:"compra_id"`
	ProductoID     uuid.UUID `json:"producto_id"`
	Cantidad       int32     `json:"cantidad"`
	PrecioUnitario int32     `json:"precio_unitario"`
}

func (q *Queries) CreateDetalleCompra(ctx context.Context, arg CreateDetalleCompraParams) error {
	_, err := q.db.Exec(ctx, createDetalleCompra,
		arg.CompraID,
		arg.ProductoID,
		arg.Cantidad,
		arg.PrecioUnitario,
	)
	return err
}

const listComprasPorCliente = `-- name: ListComprasPorCliente :many
SELECT id, cliente_id, usuario_id, subtotal, descuento, total, fecha FROM compras
WHERE cliente_id = $1
ORDER BY fecha DESC
`

func (q *Queries) ListComprasPorCliente(ctx context.Context, clienteID uuid.UUID) ([]Compra, error) {
	rows, err := q.db.Query(ctx, listComprasPorCliente, clienteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Compra{}
	for rows.Next() {
		var i Compra
		if err := rows.Scan(
			&i.ID,
			&i.ClienteID,
			&i.UsuarioID,
			&i.Subtotal,
			&i.Descuento,
			&i.Total,
			&i.Fecha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contarItemsPorClienteYCategoria = `-- name: ContarItemsPorClienteYCategoria :one
SELECT COALESCE(SUM(dc.cantidad), 0)::INTEGER AS total
FROM detalle_compra dc
JOIN compras co ON co.id = dc.compra_id
JOIN productos p ON p.id = dc.producto_id
WHERE co.cliente_id = $1
  AND p.categoria_id = $2
  AND ($3::timestamptz IS NULL OR co.fecha > $3)
`

type ContarItemsPorClienteYCategoriaParams struct {
	ClienteID   uuid.UUID          `json:"cliente_id"`
	CategoriaID uuid.UUID          `json:"categoria_id"`
	Desde       pgtype.Timestamptz `json:"desde"`
}

func (q *Queries) ContarItemsPorClienteYCategoria(ctx context.Context, arg ContarItemsPorClienteYCategoriaParams) (int32, error) {
	row := q.db.QueryRow(ctx, contarItemsPorClienteYCategoria, arg.ClienteID, arg.CategoriaID, arg.Desde)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const contarItemsPorClienteYProducto = `-- name: ContarItemsPorClienteYProducto :one
SELECT COALESCE(SUM(dc.cantidad), 0)::INTEGER AS total
FROM detalle_compra dc
JOIN compras co ON co.id = dc.compra_id
WHERE co.cliente_id = $1
  AND dc.producto_id = $2
  AND ($3::timestamptz IS NULL OR co.fecha > $3)
`

type ContarItemsPorClienteYProductoParams struct {
	ClienteID  uuid.UUID          `json:"cliente_id"`
	ProductoID uuid.UUID          `json:"producto_id"`
	Desde      pgtype.Timestamptz `json:"desde"`
}

func (q *Queries) ContarItemsPorClienteYProducto(ctx context.Context, arg ContarItemsPorClienteYProductoParams) (int32, error) {
	row := q.db.QueryRow(ctx, contarItemsPorClienteYProducto, arg.ClienteID, arg.ProductoID, arg.Desde)
	var total int32
	err := row.Scan(&total)
	return total, err
}
