// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: condiciones.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCondicion = `-- name: CreateCondicion :one
INSERT INTO condiciones (
    beneficio_id, umbral_infusiones, tipo_descuento, valor_descuento, reinicia_contador, vigente,
    tipo_trigger, dias_semana, scope_trigger, scope_trigger_categoria_id, scope_trigger_producto_id,
    scope_descuento, scope_descuento_categoria_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, beneficio_id, umbral_infusiones, tipo_descuento, valor_descuento, reinicia_contador, vigente, tipo_trigger, dias_semana, scope_trigger, scope_trigger_categoria_id, scope_trigger_producto_id, scope_descuento, scope_descuento_categoria_id
`

type CreateCondicionParams struct {
	BeneficioID               uuid.UUID   `json:"beneficio_id"`
	UmbralInfusiones          int32       `json:"umbral_infusiones"`
	TipoDescuento             string      `json:"tipo_descuento"`
	ValorDescuento            int32       `json:"valor_descuento"`
	ReiniciaContador          bool        `json:"reinicia_contador"`
	Vigente                   bool        `json:"vigente"`
	TipoTrigger               string      `json:"tipo_trigger"`
	DiasSemana                []int32     `json:"dias_semana"`
	ScopeTrigger              string      `json:"scope_trigger"`
	ScopeTriggerCategoriaID   pgtype.UUID `json:"scope_trigger_categoria_id"`
	ScopeTriggerProductoID    pgtype.UUID `json:"scope_trigger_producto_id"`
	ScopeDescuento            string      `json:"scope_descuento"`
	ScopeDescuentoCategoriaID pgtype.UUID `json:"scope_descuento_categoria_id"`
}

func (q *Queries) CreateCondicion(ctx context.Context, arg CreateCondicionParams) (Condicione, error) {
	row := q.db.QueryRow(ctx, createCondicion,
		arg.BeneficioID,
		arg.UmbralInfusiones,
		arg.TipoDescuento,
		arg.ValorDescuento,
		arg.ReiniciaContador,
		arg.Vigente,
		arg.TipoTrigger,
		arg.DiasSemana,
		arg.ScopeTrigger,
		arg.ScopeTriggerCategoriaID,
		arg.ScopeTriggerProductoID,
		arg.ScopeDescuento,
		arg.ScopeDescuentoCategoriaID,
	)
	var i Condicione
	err := row.Scan(
		&i.ID,
		&i.BeneficioID,
		&i.UmbralInfusiones,
		&i.TipoDescuento,
		&i.ValorDescuento,
		&i.ReiniciaContador,
		&i.Vigente,
		&i.TipoTrigger,
		&i.DiasSemana,
		&i.ScopeTrigger,
		&i.ScopeTriggerCategoriaID,
		&i.ScopeTriggerProductoID,
		&i.ScopeDescuento,
		&i.ScopeDescuentoCategoriaID,
	)
	return i, err
}

const getCondicionParaCanje = `-- name: GetCondicionParaCanje :one
SELECT
    c.id,
    c.beneficio_id,
    c.umbral_infusiones,
    c.tipo_descuento,
    c.valor_descuento,
    c.reinicia_contador,
    c.vigente,
    c.tipo_trigger,
    c.dias_semana,
    c.scope_trigger,
    c.scope_trigger_categoria_id,
    c.scope_trigger_producto_id,
    c.scope_descuento,
    c.scope_descuento_categoria_id,
    b.activo AS beneficio_activo,
    EXISTS(
        SELECT 1 FROM beneficio_instituciones bi
        WHERE bi.beneficio_id = b.id AND bi.institucion_id = $2
    ) AS institucion_match
FROM condiciones c
JOIN beneficios b ON b.id = c.beneficio_id
WHERE c.id = $1
`

type GetCondicionParaCanjeParams struct {
	ID            uuid.UUID `json:"id"`
	InstitucionID uuid.UUID `json:"institucion_id"`
}

type GetCondicionParaCanjeRow struct {
	ID                        uuid.UUID   `json:"id"`
	BeneficioID               uuid.UUID   `json:"beneficio_id"`
	UmbralInfusiones          int32       `json:"umbral_infusiones"`
	TipoDescuento             string      `json:"tipo_descuento"`
	ValorDescuento            int32       `json:"valor_descuento"`
	ReiniciaContador          bool        `json:"reinicia_contador"`
	Vigente                   bool        `json:"vigente"`
	TipoTrigger               string      `json:"tipo_trigger"`
	DiasSemana                []int32     `json:"dias_semana"`
	ScopeTrigger              string      `json:"scope_trigger"`
	ScopeTriggerCategoriaID   pgtype.UUID `json:"scope_trigger_categoria_id"`
	ScopeTriggerProductoID    pgtype.UUID `json:"scope_trigger_producto_id"`
	ScopeDescuento            string      `json:"scope_descuento"`
	ScopeDescuentoCategoriaID pgtype.UUID `json:"scope_descuento_categoria_id"`
	BeneficioActivo           bool        `json:"beneficio_activo"`
	InstitucionMatch          bool        `json:"institucion_match"`
}

func (q *Queries) GetCondicionParaCanje(ctx context.Context, arg GetCondicionParaCanjeParams) (GetCondicionParaCanjeRow, error) {
	row := q.db.QueryRow(ctx, getCondicionParaCanje, arg.ID, arg.InstitucionID)
	var i GetCondicionParaCanjeRow
	err := row.Scan(
		&i.ID,
		&i.BeneficioID,
		&i.UmbralInfusiones,
		&i.TipoDescuento,
		&i.ValorDescuento,
		&i.ReiniciaContador,
		&i.Vigente,
		&i.TipoTrigger,
		&i.DiasSemana,
		&i.ScopeTrigger,
		&i.ScopeTriggerCategoriaID,
		&i.ScopeTriggerProductoID,
		&i.ScopeDescuento,
		&i.ScopeDescuentoCategoriaID,
		&i.BeneficioActivo,
		&i.InstitucionMatch,
	)
	return i, err
}

const listCondicionesPorBeneficio = `-- name: ListCondicionesPorBeneficio :many
SELECT id, beneficio_id, umbral_infusiones, tipo_descuento, valor_descuento, reinicia_contador, vigente, tipo_trigger, dias_semana, scope_trigger, scope_trigger_categoria_id, scope_trigger_producto_id, scope_descuento, scope_descuento_categoria_id FROM condiciones
WHERE beneficio_id = $1
ORDER BY umbral_infusiones ASC
`

func (q *Queries) ListCondicionesPorBeneficio(ctx context.Context, beneficioID uuid.UUID) ([]Condicione, error) {
	rows, err := q.db.Query(ctx, listCondicionesPorBeneficio, beneficioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Condicione{}
	for rows.Next() {
		var i Condicione
		if err := rows.Scan(
			&i.ID,
			&i.BeneficioID,
			&i.UmbralInfusiones,
			&i.TipoDescuento,
			&i.ValorDescuento,
			&i.ReiniciaContador,
			&i.Vigente,
			&i.TipoTrigger,
			&i.DiasSemana,
			&i.ScopeTrigger,
			&i.ScopeTriggerCategoriaID,
			&i.ScopeTriggerProductoID,
			&i.ScopeDescuento,
			&i.ScopeDescuentoCategoriaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCondicionesPorInstitucion = `-- name: ListCondicionesPorInstitucion :many
SELECT
    c.id AS condicion_id,
    c.umbral_infusiones,
    c.tipo_descuento,
    c.valor_descuento,
    c.reinicia_contador,
    c.tipo_trigger,
    c.dias_semana,
    c.scope_trigger,
    c.scope_trigger_categoria_id,
    c.scope_trigger_producto_id,
    c.scope_descuento,
    c.scope_descuento_categoria_id,
    b.nombre AS beneficio_nombre
FROM condiciones c
JOIN beneficios b ON b.id = c.beneficio_id
JOIN beneficio_instituciones bi ON bi.beneficio_id = b.id
WHERE bi.institucion_id = $1
  AND c.vigente = true
  AND b.activo = true
ORDER BY c.umbral_infusiones ASC
`

type ListCondicionesPorInstitucionRow struct {
	CondicionID               uuid.UUID   `json:"condicion_id"`
	UmbralInfusiones          int32       `json:"umbral_infusiones"`
	TipoDescuento             string      `json:"tipo_descuento"`
	ValorDescuento            int32       `json:"valor_descuento"`
	ReiniciaContador          bool        `json:"reinicia_contador"`
	TipoTrigger               string      `json:"tipo_trigger"`
	DiasSemana                []int32     `json:"dias_semana"`
	ScopeTrigger              string      `json:"scope_trigger"`
	ScopeTriggerCategoriaID   pgtype.UUID `json:"scope_trigger_categoria_id"`
	ScopeTriggerProductoID    pgtype.UUID `json:"scope_trigger_producto_id"`
	ScopeDescuento            string      `json:"scope_descuento"`
	ScopeDescuentoCategoriaID pgtype.UUID `json:"scope_descuento_categoria_id"`
	BeneficioNombre           string      `json:"beneficio_nombre"`
}

func (q *Queries) ListCondicionesPorInstitucion(ctx context.Context, institucionID pgtype.UUID) ([]ListCondicionesPorInstitucionRow, error) {
	rows, err := q.db.Query(ctx, listCondicionesPorInstitucion, institucionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCondicionesPorInstitucionRow{}
	for rows.Next() {
		var i ListCondicionesPorInstitucionRow
		if err := rows.Scan(
			&i.CondicionID,
			&i.UmbralInfusiones,
			&i.TipoDescuento,
			&i.ValorDescuento,
			&i.ReiniciaContador,
			&i.TipoTrigger,
			&i.DiasSemana,
			&i.ScopeTrigger,
			&i.ScopeTriggerCategoriaID,
			&i.ScopeTriggerProductoID,
			&i.ScopeDescuento,
			&i.ScopeDescuentoCategoriaID,
			&i.BeneficioNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodasCondiciones = `-- name: ListTodasCondiciones :many
SELECT id, beneficio_id, umbral_infusiones, tipo_descuento, valor_descuento, reinicia_contador, vigente, tipo_trigger, dias_semana, scope_trigger, scope_trigger_categoria_id, scope_trigger_producto_id, scope_descuento, scope_descuento_categoria_id FROM condiciones
ORDER BY beneficio_id, umbral_infusiones ASC
`

func (q *Queries) ListTodasCondiciones(ctx context.Context) ([]Condicione, error) {
	rows, err := q.db.Query(ctx, listTodasCondiciones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Condicione{}
	for rows.Next() {
		var i Condicione
		if err := rows.Scan(
			&i.ID,
			&i.BeneficioID,
			&i.UmbralInfusiones,
			&i.TipoDescuento,
			&i.ValorDescuento,
			&i.ReiniciaContador,
			&i.Vigente,
			&i.TipoTrigger,
			&i.DiasSemana,
			&i.ScopeTrigger,
			&i.ScopeTriggerCategoriaID,
			&i.ScopeTriggerProductoID,
			&i.ScopeDescuento,
			&i.ScopeDescuentoCategoriaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCondicion = `-- name: UpdateCondicion :one
UPDATE condiciones
SET umbral_infusiones            = $2,
    tipo_descuento               = $3,
    valor_descuento              = $4,
    reinicia_contador            = $5,
    vigente                      = $6,
    tipo_trigger                 = $7,
    dias_semana                  = $8,
    scope_trigger                = $9,
    scope_trigger_categoria_id   = $10,
    scope_trigger_producto_id    = $11,
    scope_descuento              = $12,
    scope_descuento_categoria_id = $13
WHERE id = $1
RETURNING id, beneficio_id, umbral_infusiones, tipo_descuento, valor_descuento, reinicia_contador, vigente, tipo_trigger, dias_semana, scope_trigger, scope_trigger_categoria_id, scope_trigger_producto_id, scope_descuento, scope_descuento_categoria_id
`

type UpdateCondicionParams struct {
	ID                        uuid.UUID   `json:"id"`
	UmbralInfusiones          int32       `json:"umbral_infusiones"`
	TipoDescuento             string      `json:"tipo_descuento"`
	ValorDescuento            int32       `json:"valor_descuento"`
	ReiniciaContador          bool        `json:"reinicia_contador"`
	Vigente                   bool        `json:"vigente"`
	TipoTrigger               string      `json:"tipo_trigger"`
	DiasSemana                []int32     `json:"dias_semana"`
	ScopeTrigger              string      `json:"scope_trigger"`
	ScopeTriggerCategoriaID   pgtype.UUID `json:"scope_trigger_categoria_id"`
	ScopeTriggerProductoID    pgtype.UUID `json:"scope_trigger_producto_id"`
	ScopeDescuento            string      `json:"scope_descuento"`
	ScopeDescuentoCategoriaID pgtype.UUID `json:"scope_descuento_categoria_id"`
}

func (q *Queries) UpdateCondicion(ctx context.Context, arg UpdateCondicionParams) (Condicione, error) {
	row := q.db.QueryRow(ctx, updateCondicion,
		arg.ID,
		arg.UmbralInfusiones,
		arg.TipoDescuento,
		arg.ValorDescuento,
		arg.ReiniciaContador,
		arg.Vigente,
		arg.TipoTrigger,
		arg.DiasSemana,
		arg.ScopeTrigger,
		arg.ScopeTriggerCategoriaID,
		arg.ScopeTriggerProductoID,
		arg.ScopeDescuento,
		arg.ScopeDescuentoCategoriaID,
	)
	var i Condicione
	err := row.Scan(
		&i.ID,
		&i.BeneficioID,
		&i.UmbralInfusiones,
		&i.TipoDescuento,
		&i.ValorDescuento,
		&i.ReiniciaContador,
		&i.Vigente,
		&i.TipoTrigger,
		&i.DiasSemana,
		&i.ScopeTrigger,
		&i.ScopeTriggerCategoriaID,
		&i.ScopeTriggerProductoID,
		&i.ScopeDescuento,
		&i.ScopeDescuentoCategoriaID,
	)
	return i, err
}

const deleteCondicionesPorBeneficio = `-- name: DeleteCondicionesPorBeneficio :exec
DELETE FROM condiciones WHERE beneficio_id = $1
`

func (q *Queries) DeleteCondicionesPorBeneficio(ctx context.Context, beneficioID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCondicionesPorBeneficio, beneficioID)
	return err
}
