// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: condiciones.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCondicion = `-- name: CreateCondicion :one
INSERT INTO condiciones (beneficio_id, umbral_infusiones, tipo_descuento, valor_descuento, reinicia_contador, vigente)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, beneficio_id, umbral_infusiones, tipo_descuento, valor_descuento, reinicia_contador, vigente
`

type CreateCondicionParams struct {
	BeneficioID      uuid.UUID `json:"beneficio_id"`
	UmbralInfusiones int32     `json:"umbral_infusiones"`
	TipoDescuento    string    `json:"tipo_descuento"`
	ValorDescuento   int32     `json:"valor_descuento"`
	ReiniciaContador bool      `json:"reinicia_contador"`
	Vigente          bool      `json:"vigente"`
}

func (q *Queries) CreateCondicion(ctx context.Context, arg CreateCondicionParams) (Condicione, error) {
	row := q.db.QueryRow(ctx, createCondicion,
		arg.BeneficioID,
		arg.UmbralInfusiones,
		arg.TipoDescuento,
		arg.ValorDescuento,
		arg.ReiniciaContador,
		arg.Vigente,
	)
	var i Condicione
	err := row.Scan(
		&i.ID,
		&i.BeneficioID,
		&i.UmbralInfusiones,
		&i.TipoDescuento,
		&i.ValorDescuento,
		&i.ReiniciaContador,
		&i.Vigente,
	)
	return i, err
}

const getCondicionParaCanje = `-- name: GetCondicionParaCanje :one
SELECT
    c.id,
    c.beneficio_id,
    c.umbral_infusiones,
    c.tipo_descuento,
    c.valor_descuento,
    c.reinicia_contador,
    c.vigente,
    b.institucion_id,
    b.activo AS beneficio_activo
FROM condiciones c
JOIN beneficios b ON b.id = c.beneficio_id
WHERE c.id = $1
`

type GetCondicionParaCanjeRow struct {
	ID               uuid.UUID `json:"id"`
	BeneficioID      uuid.UUID `json:"beneficio_id"`
	UmbralInfusiones int32     `json:"umbral_infusiones"`
	TipoDescuento    string    `json:"tipo_descuento"`
	ValorDescuento   int32     `json:"valor_descuento"`
	ReiniciaContador bool      `json:"reinicia_contador"`
	Vigente          bool      `json:"vigente"`
	InstitucionID    uuid.UUID `json:"institucion_id"`
	BeneficioActivo  bool      `json:"beneficio_activo"`
}

func (q *Queries) GetCondicionParaCanje(ctx context.Context, id uuid.UUID) (GetCondicionParaCanjeRow, error) {
	row := q.db.QueryRow(ctx, getCondicionParaCanje, id)
	var i GetCondicionParaCanjeRow
	err := row.Scan(
		&i.ID,
		&i.BeneficioID,
		&i.UmbralInfusiones,
		&i.TipoDescuento,
		&i.ValorDescuento,
		&i.ReiniciaContador,
		&i.Vigente,
		&i.InstitucionID,
		&i.BeneficioActivo,
	)
	return i, err
}

const listCondicionesPorBeneficio = `-- name: ListCondicionesPorBeneficio :many
SELECT id, beneficio_id, umbral_infusiones, tipo_descuento, valor_descuento, reinicia_contador, vigente FROM condiciones
WHERE beneficio_id = $1
ORDER BY umbral_infusiones ASC
`

func (q *Queries) ListCondicionesPorBeneficio(ctx context.Context, beneficioID uuid.UUID) ([]Condicione, error) {
	rows, err := q.db.Query(ctx, listCondicionesPorBeneficio, beneficioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Condicione{}
	for rows.Next() {
		var i Condicione
		if err := rows.Scan(
			&i.ID,
			&i.BeneficioID,
			&i.UmbralInfusiones,
			&i.TipoDescuento,
			&i.ValorDescuento,
			&i.ReiniciaContador,
			&i.Vigente,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCondicionesPorInstitucion = `-- name: ListCondicionesPorInstitucion :many
SELECT
    c.id AS condicion_id,
    c.umbral_infusiones,
    c.tipo_descuento,
    c.valor_descuento,
    c.reinicia_contador,
    b.nombre AS beneficio_nombre
FROM condiciones c
JOIN beneficios b ON b.id = c.beneficio_id
WHERE b.institucion_id = $1
  AND c.vigente = true
  AND b.activo = true
ORDER BY c.umbral_infusiones ASC
`

type ListCondicionesPorInstitucionRow struct {
	CondicionID      uuid.UUID `json:"condicion_id"`
	UmbralInfusiones int32     `json:"umbral_infusiones"`
	TipoDescuento    string    `json:"tipo_descuento"`
	ValorDescuento   int32     `json:"valor_descuento"`
	ReiniciaContador bool      `json:"reinicia_contador"`
	BeneficioNombre  string    `json:"beneficio_nombre"`
}

func (q *Queries) ListCondicionesPorInstitucion(ctx context.Context, institucionID uuid.UUID) ([]ListCondicionesPorInstitucionRow, error) {
	rows, err := q.db.Query(ctx, listCondicionesPorInstitucion, institucionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCondicionesPorInstitucionRow{}
	for rows.Next() {
		var i ListCondicionesPorInstitucionRow
		if err := rows.Scan(
			&i.CondicionID,
			&i.UmbralInfusiones,
			&i.TipoDescuento,
			&i.ValorDescuento,
			&i.ReiniciaContador,
			&i.BeneficioNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodasCondiciones = `-- name: ListTodasCondiciones :many
SELECT id, beneficio_id, umbral_infusiones, tipo_descuento, valor_descuento, reinicia_contador, vigente FROM condiciones
ORDER BY beneficio_id, umbral_infusiones ASC
`

func (q *Queries) ListTodasCondiciones(ctx context.Context) ([]Condicione, error) {
	rows, err := q.db.Query(ctx, listTodasCondiciones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Condicione{}
	for rows.Next() {
		var i Condicione
		if err := rows.Scan(
			&i.ID,
			&i.BeneficioID,
			&i.UmbralInfusiones,
			&i.TipoDescuento,
			&i.ValorDescuento,
			&i.ReiniciaContador,
			&i.Vigente,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCondicion = `-- name: UpdateCondicion :one
UPDATE condiciones
SET umbral_infusiones = $2,
    tipo_descuento    = $3,
    valor_descuento   = $4,
    reinicia_contador = $5,
    vigente           = $6
WHERE id = $1
RETURNING id, beneficio_id, umbral_infusiones, tipo_descuento, valor_descuento, reinicia_contador, vigente
`

type UpdateCondicionParams struct {
	ID               uuid.UUID `json:"id"`
	UmbralInfusiones int32     `json:"umbral_infusiones"`
	TipoDescuento    string    `json:"tipo_descuento"`
	ValorDescuento   int32     `json:"valor_descuento"`
	ReiniciaContador bool      `json:"reinicia_contador"`
	Vigente          bool      `json:"vigente"`
}

func (q *Queries) UpdateCondicion(ctx context.Context, arg UpdateCondicionParams) (Condicione, error) {
	row := q.db.QueryRow(ctx, updateCondicion,
		arg.ID,
		arg.UmbralInfusiones,
		arg.TipoDescuento,
		arg.ValorDescuento,
		arg.ReiniciaContador,
		arg.Vigente,
	)
	var i Condicione
	err := row.Scan(
		&i.ID,
		&i.BeneficioID,
		&i.UmbralInfusiones,
		&i.TipoDescuento,
		&i.ValorDescuento,
		&i.ReiniciaContador,
		&i.Vigente,
	)
	return i, err
}
