// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instituciones.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createInstitucion = `-- name: CreateInstitucion :one
INSERT INTO instituciones (nombre)
VALUES ($1)
RETURNING id, nombre, activa, created_at
`

func (q *Queries) CreateInstitucion(ctx context.Context, nombre string) (Institucione, error) {
	row := q.db.QueryRow(ctx, createInstitucion, nombre)
	var i Institucione
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Activa,
		&i.CreatedAt,
	)
	return i, err
}

const getInstitucionByID = `-- name: GetInstitucionByID :one
SELECT id, nombre, activa, created_at FROM instituciones
WHERE id = $1
`

func (q *Queries) GetInstitucionByID(ctx context.Context, id uuid.UUID) (Institucione, error) {
	row := q.db.QueryRow(ctx, getInstitucionByID, id)
	var i Institucione
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Activa,
		&i.CreatedAt,
	)
	return i, err
}

const listInstituciones = `-- name: ListInstituciones :many
SELECT id, nombre, activa, created_at FROM instituciones
ORDER BY nombre
`

func (q *Queries) ListInstituciones(ctx context.Context) ([]Institucione, error) {
	rows, err := q.db.Query(ctx, listInstituciones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Institucione{}
	for rows.Next() {
		var i Institucione
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Activa,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstitucion = `-- name: UpdateInstitucion :one
UPDATE instituciones
SET nombre = $2,
    activa = $3
WHERE id = $1
RETURNING id, nombre, activa, created_at
`

type UpdateInstitucionParams struct {
	ID     uuid.UUID `json:"id"`
	Nombre string    `json:"nombre"`
	Activa bool      `json:"activa"`
}

func (q *Queries) UpdateInstitucion(ctx context.Context, arg UpdateInstitucionParams) (Institucione, error) {
	row := q.db.QueryRow(ctx, updateInstitucion, arg.ID, arg.Nombre, arg.Activa)
	var i Institucione
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Activa,
		&i.CreatedAt,
	)
	return i, err
}
