// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Beneficio struct {
	ID     uuid.UUID `json:"id"`
	Nombre string    `json:"nombre"`
	Activo bool      `json:"activo"`
}

type BeneficioInstitucionRow struct {
	BeneficioID        uuid.UUID `json:"beneficio_id"`
	InstitucionID      uuid.UUID `json:"institucion_id"`
	InstitucionNombre  string    `json:"institucion_nombre"`
}

type Canje struct {
	ID                uuid.UUID          `json:"id"`
	ClienteID         uuid.UUID          `json:"cliente_id"`
	BeneficioID       uuid.UUID          `json:"beneficio_id"`
	CondicionID       uuid.UUID          `json:"condicion_id"`
	CompraID          uuid.UUID          `json:"compra_id"`
	UsuarioID         uuid.UUID          `json:"usuario_id"`
	DescuentoAplicado int32              `json:"descuento_aplicado"`
	Fecha             pgtype.Timestamptz `json:"fecha"`
}

type Categoria struct {
	ID      uuid.UUID `json:"id"`
	Nombre  string    `json:"nombre"`
	Seccion string    `json:"seccion"`
	Orden   int32     `json:"orden"`
}

type Cliente struct {
	ID                 uuid.UUID          `json:"id"`
	Dni                string             `json:"dni"`
	Nombre             string             `json:"nombre"`
	Email              pgtype.Text        `json:"email"`
	InstitucionID      uuid.NullUUID      `json:"institucion_id"`
	ContadorInfusiones int32              `json:"contador_infusiones"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Compra struct {
	ID        uuid.UUID          `json:"id"`
	ClienteID uuid.UUID          `json:"cliente_id"`
	UsuarioID uuid.UUID          `json:"usuario_id"`
	Subtotal  int32              `json:"subtotal"`
	Descuento int32              `json:"descuento"`
	Total     int32              `json:"total"`
	Fecha     pgtype.Timestamptz `json:"fecha"`
}

type Condicione struct {
	ID                        uuid.UUID          `json:"id"`
	BeneficioID               uuid.UUID          `json:"beneficio_id"`
	UmbralInfusiones          int32              `json:"umbral_infusiones"`
	TipoDescuento             string             `json:"tipo_descuento"`
	ValorDescuento            int32              `json:"valor_descuento"`
	ReiniciaContador          bool               `json:"reinicia_contador"`
	Vigente                   bool               `json:"vigente"`
	TipoTrigger               string             `json:"tipo_trigger"`
	DiasSemana                []int32            `json:"dias_semana"`
	ScopeTrigger              string             `json:"scope_trigger"`
	ScopeTriggerCategoriaID   pgtype.UUID        `json:"scope_trigger_categoria_id"`
	ScopeTriggerProductoID    pgtype.UUID        `json:"scope_trigger_producto_id"`
	ScopeDescuento            string             `json:"scope_descuento"`
	ScopeDescuentoCategoriaID pgtype.UUID        `json:"scope_descuento_categoria_id"`
}

type DetalleCompra struct {
	ID             uuid.UUID `json:"id"`
	CompraID       uuid.UUID `json:"compra_id"`
	ProductoID     uuid.UUID `json:"producto_id"`
	Cantidad       int32     `json:"cantidad"`
	PrecioUnitario int32     `json:"precio_unitario"`
}

type Institucione struct {
	ID        uuid.UUID          `json:"id"`
	Nombre    string             `json:"nombre"`
	Activa    bool               `json:"activa"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Producto struct {
	ID          uuid.UUID `json:"id"`
	CategoriaID uuid.UUID `json:"categoria_id"`
	Nombre      string    `json:"nombre"`
	Precio      int32     `json:"precio"`
	EsInfusion  bool      `json:"es_infusion"`
	Activo      bool      `json:"activo"`
	Descripcion string    `json:"descripcion"`
}

type UsuariosSistema struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Rol          string    `json:"rol"`
	Activo       bool      `json:"activo"`
}
