// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: productos.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createProducto = `-- name: CreateProducto :one
INSERT INTO productos (categoria_id, nombre, precio, es_infusion)
VALUES ($1, $2, $3, $4)
RETURNING id, categoria_id, nombre, precio, es_infusion, activo
`

type CreateProductoParams struct {
	CategoriaID uuid.UUID `json:"categoria_id"`
	Nombre      string    `json:"nombre"`
	Precio      int32     `json:"precio"`
	EsInfusion  bool      `json:"es_infusion"`
}

func (q *Queries) CreateProducto(ctx context.Context, arg CreateProductoParams) (Producto, error) {
	row := q.db.QueryRow(ctx, createProducto,
		arg.CategoriaID,
		arg.Nombre,
		arg.Precio,
		arg.EsInfusion,
	)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.CategoriaID,
		&i.Nombre,
		&i.Precio,
		&i.EsInfusion,
		&i.Activo,
	)
	return i, err
}

const getProductoPorID = `-- name: GetProductoPorID :one
SELECT id, categoria_id, nombre, precio, es_infusion, activo FROM productos
WHERE id = $1
`

func (q *Queries) GetProductoPorID(ctx context.Context, id uuid.UUID) (Producto, error) {
	row := q.db.QueryRow(ctx, getProductoPorID, id)
	var i Producto
	err := row.Scan(
		&i.ID,
		&i.CategoriaID,
		&i.Nombre,
		&i.Precio,
		&i.EsInfusion,
		&i.Activo,
	)
	return i, err
}

const listProductosActivos = `-- name: ListProductosActivos :many
SELECT id, categoria_id, nombre, precio, es_infusion, activo FROM productos
WHERE activo = true
ORDER BY nombre
`

func (q *Queries) ListProductosActivos(ctx context.Context) ([]Producto, error) {
	rows, err := q.db.Query(ctx, listProductosActivos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Producto{}
	for rows.Next() {
		var i Producto
		if err := rows.Scan(
			&i.ID,
			&i.CategoriaID,
			&i.Nombre,
			&i.Precio,
			&i.EsInfusion,
			&i.Activo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
