// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateInstitucion(ctx context.Context, nombre string) (Institucione, error)
	CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (UsuariosSistema, error)
	GetInstitucionByID(ctx context.Context, id uuid.UUID) (Institucione, error)
	GetUsuarioByEmail(ctx context.Context, email string) (UsuariosSistema, error)
	GetUsuarioByID(ctx context.Context, id uuid.UUID) (UsuariosSistema, error)
	ListInstituciones(ctx context.Context) ([]Institucione, error)
	ListUsuarios(ctx context.Context) ([]UsuariosSistema, error)
	UpdateInstitucion(ctx context.Context, arg UpdateInstitucionParams) (Institucione, error)
	UpdateUsuario(ctx context.Context, arg UpdateUsuarioParams) (UsuariosSistema, error)
	UpdateUsuarioPassword(ctx context.Context, arg UpdateUsuarioPasswordParams) error
}

var _ Querier = (*Queries)(nil)
