// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usuarios.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUsuario = `-- name: CreateUsuario :one
INSERT INTO usuarios_sistema (email, password_hash, rol)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, rol, activo
`

type CreateUsuarioParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Rol          string `json:"rol"`
}

func (q *Queries) CreateUsuario(ctx context.Context, arg CreateUsuarioParams) (UsuariosSistema, error) {
	row := q.db.QueryRow(ctx, createUsuario, arg.Email, arg.PasswordHash, arg.Rol)
	var i UsuariosSistema
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Rol,
		&i.Activo,
	)
	return i, err
}

const getUsuarioByEmail = `-- name: GetUsuarioByEmail :one
SELECT id, email, password_hash, rol, activo FROM usuarios_sistema
WHERE email = $1
`

func (q *Queries) GetUsuarioByEmail(ctx context.Context, email string) (UsuariosSistema, error) {
	row := q.db.QueryRow(ctx, getUsuarioByEmail, email)
	var i UsuariosSistema
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Rol,
		&i.Activo,
	)
	return i, err
}

const getUsuarioByID = `-- name: GetUsuarioByID :one
SELECT id, email, password_hash, rol, activo FROM usuarios_sistema
WHERE id = $1
`

func (q *Queries) GetUsuarioByID(ctx context.Context, id uuid.UUID) (UsuariosSistema, error) {
	row := q.db.QueryRow(ctx, getUsuarioByID, id)
	var i UsuariosSistema
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Rol,
		&i.Activo,
	)
	return i, err
}

const listUsuarios = `-- name: ListUsuarios :many
SELECT id, email, password_hash, rol, activo FROM usuarios_sistema
ORDER BY email
`

func (q *Queries) ListUsuarios(ctx context.Context) ([]UsuariosSistema, error) {
	rows, err := q.db.Query(ctx, listUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsuariosSistema{}
	for rows.Next() {
		var i UsuariosSistema
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Rol,
			&i.Activo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUsuario = `-- name: UpdateUsuario :one
UPDATE usuarios_sistema
SET email = $2,
    rol = $3,
    activo = $4
WHERE id = $1
RETURNING id, email, password_hash, rol, activo
`

type UpdateUsuarioParams struct {
	ID     uuid.UUID `json:"id"`
	Email  string    `json:"email"`
	Rol    string    `json:"rol"`
	Activo bool      `json:"activo"`
}

func (q *Queries) UpdateUsuario(ctx context.Context, arg UpdateUsuarioParams) (UsuariosSistema, error) {
	row := q.db.QueryRow(ctx, updateUsuario,
		arg.ID,
		arg.Email,
		arg.Rol,
		arg.Activo,
	)
	var i UsuariosSistema
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Rol,
		&i.Activo,
	)
	return i, err
}

const updateUsuarioPassword = `-- name: UpdateUsuarioPassword :exec
UPDATE usuarios_sistema
SET password_hash = $2
WHERE id = $1
`

type UpdateUsuarioPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUsuarioPassword(ctx context.Context, arg UpdateUsuarioPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUsuarioPassword, arg.ID, arg.PasswordHash)
	return err
}
